version: "3"
services: 
    nginx:
        build: 
            context: ./WTBeiboot_SS21_Albus/Nginx
            dockerfile: Dockerfile
        ports: 
            - 80:80
        restart: always
    client:
        build:
            context: ./WTBeiboot_SS21_Albus/ClientApp
            dockerfile: Dockerfile
        ports: 
            - 5000:80
    dncapi:
        build: 
            context: ./
            dockerfile: Dockerfile
        ports: 
            - 3000:80
        volumes:
            - ./data:/mnt
        