version: "3"
services: 
    frontend:
        build: ./frontend
        ports: 
            - 80:80
        expose:
            - "80"
    backend:
        build: 
            context: ./backend
            dockerfile: WTBeiboot_SS21_Albus/Dockerfile
        ports: 
            - 8080:80
        volumes:
            - ./data:/mnt
        